stages:
  - archive
  - upload

archive:
  stage: archive
  image: alpine:3.17
  before_script:
    - apk add zip
  script:
    - zip -r ${CI_PROJECT_NAME}.zip ./src > /dev/null 2>&1
  artifacts:
    paths:
      - ${CI_PROJECT_NAME}.zip
    expire_in: 1h
    when: on_success

upload:
  stage: upload
  dependencies:
    - archive
  image: 
    name: amazon/aws-cli:2.10.0
    entrypoint: [""]
  script:
    - if [ ${CI_COMMIT_BRANCH} == "master" ]; then STAGE="pro"; else STAGE="dev"; fi
    - aws --endpoint-url=${NCP_S3_URL} s3 cp ${CI_PROJECT_NAME}.zip s3://build-result/${STAGE}/${CI_PROJECT_NAME}.zip
