version: "2"

services:
  nginx:
   image: nginx
   container_name: nginx
   volumes:
    - ./config:/etc/nginx/
    - ../public:/usr/share/nginx/html/
   ports:
    - "80:80"
   environment:
    - NGINX_HOST=localhost
    - NGINX_PORT=80
#    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/mysite.template > /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"


# networks: 
#  default:
#    external: 
#      name: elastic